FROM public.ecr.aws/lambda/nodejs:18 as builder
WORKDIR /app
RUN corepack enable pnpm
COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./coffee-scraper ./
RUN pnpm i
RUN pnpm -F coffee-scraper build
    
FROM public.ecr.aws/lambda/nodejs:18
WORKDIR ${LAMBDA_TASK_ROOT}
COPY --from=builder /app/dist/* ./
CMD ["index.handler"]