import './globals.css'
import '@mantine/core/styles.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ReactQueryProvider } from './ReactQueryProvider'
import { CustomErrorBoundary } from './components/ErrorBoundary'
import { ColorSchemeScript, MantineProvider } from '@mantine/core'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
        <CustomErrorBoundary>
          <MantineProvider>
            <ReactQueryProvider>{children}</ReactQueryProvider>
          </MantineProvider>
        </CustomErrorBoundary>
      </body>
    </html>
  )
}
