import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ErrorBoundary } from 'react-error-boundary'
import './globals.css'
import { ReactQueryProvider } from './ReactQueryProvider'
import { CustomErrorBoundary } from './components/ErrorBoundary'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CustomErrorBoundary>
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </CustomErrorBoundary>
      </body>
    </html>
  )
}
